# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-20 21:09
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '003_card_customer_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='active',
            field=djstripe.fields.StripeBooleanField(default=True),
        ),
    ]
