# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-05-09 15:12
from __future__ import unicode_literals

from django.db import migrations
import djstripe.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djstripe', '0004_plan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at',
            field=djstripe.fields.StripeDateTimeField(null=True),
        ),
    ]
